name: build
on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Text to image
        run: DISABLE_TELEMETRY=YES python text_to_image.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            *.png
