name: image-to-image
on: [push, workflow_dispatch]

jobs:
  image-to-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface/
          key: ${{ runner.os }}-huggingface

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: 3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Image-to-image
        run: python image_to_image.py
        env:
          DO_NOT_TRACK: 1

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: artifact
          path: |
            *.png
